# api call for signup
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username":"user5",
    "email":"user@gmail.com",
    "password":"user123"
}


# api call for token generation
###
POST http://127.0.0.1:8000/token/
Content-Type: application/json

{
    "username":"user5",
    "password":"user123"
}


# api call for create grocery
###
POST http://127.0.0.1:8000/grocery/
Content-Type: application/json
Authorization: Token 261f700073c7de81d39d5326ab20a1275da791d9

{
    "item_name": "Paper Towels",
    "category": "OTH",
    "price": "12.00",
    "quantity": 1,
    "expiry_date": "2029-12-31"
}


# api call for list grocery
###
GET http://127.0.0.1:8000/grocery/
Accept: application/json
Authorization: Token 261f700073c7de81d39d5326ab20a1275da791d9


# api call for retrieve grocery
###
GET http://127.0.0.1:8000/grocery/10/
Accept: application/json
Authorization: Token 261f700073c7de81d39d5326ab20a1275da791d9



# api call for update grocery
###
PUT http://127.0.0.1:8000/grocery/4/
Content-Type: application/json
Authorization: Token 261f700073c7de81d39d5326ab20a1275da791d9

{
    "item_name": "Cold Brew Coffee",
    "category": "BEV",
    "price": "5.50",
    "quantity": 18,
    "expiry_date": "2026-05-20"
}



# api call for delete grocery
###
DELETE http://127.0.0.1:8000/grocery/4/
Authorization: Token 261f700073c7de81d39d5326ab20a1275da791d9
